### ISSUE TITLE
Multiple Server Connections

### ISSUE THREAD

**Issue by calmdev** [felixheck/akaya#1]
Hey! I'm trying this out with a hapi server that has three connections:
* admin
* api
* client

Registering `akaya` with a hapi server that has multiple connections causes it to fail [when calling](https://github.com/felixheck/akaya/blob/master/src/index.js#L121) `server.lookup(id)` method. It works fine when registered to a single connection, but what do you think about supporting server labels so it can be registered with multiple connections? Maybe we can pass the label along so it can select a connection?`server.select(label).lookup(id)` ... or maybe I'm just missing something and it's already supported?

Here's a copy of the actual error:

```shell
Debug: internal, implementation, error
  Error: Uncaught error: Method not available when the selection has more than one connection or none
  at Object.exports.assert (node_modules/hapi/node_modules/hoek/lib/index.js:736:11)
  at internals.Plugin.lookup (node_modules/hapi/lib/plugin.js:526:10)
  at decorator [as aka] (node_modules/akaya/lib/index.js:120:42)
```

More info:

[Hapi server.lookup](https://github.com/hapijs/hapi/blob/master/API.md#serverlookupid)
> When the server contains more than one connection, each server.connections array member provides its own connection.lookup() method.

**Comment by felixheck** [comment]
Hey @calmdev,

sorry, I read the issue only now. So thanks for your request. You are right, it's not support yet.

But I just added multi-connection support to **akaya**. You don't have to pass any additional options, **akaya** works across multiple connections.

Feel free to update your project to akaya v1.0.1 :)

**Comment by calmdev** [comment]
Nice! The `v1.0.1` release is perfect.

**Comment by felixheck** [comment]
@calmdev Maybe there will be a refactoring for performance issues the next days but the API won't change. 

Feel free to push in further improvements and feature requests.

**Comment by calmdev** [comment]
Ok, I'll post back if I have more ideas. I'm using this in the handlers for controllers and I've also made a simple helper to use this with dustjs in the views. Def _hapi_ with it so far.
